# Generated by Django 5.2.5 on 2025-08-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_customer_reservation_customuser'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
