# Justfile - automatisation Django (Windows + PowerShell)
set shell := ["powershell", "-Command"]

# Lancer le serveur Django
run:
    docker compose exec koobfood uv run manage.py runserver 0.0.0.0:8000

# Créer les migrations
makemigrations:
    docker compose exec koobfood uv run manage.py makemigrations

# Appliquer les migrations
migrate:
    docker compose exec koobfood uv run manage.py migrate

# Créer un superutilisateur
superuser:
    uv run python manage.py createsuperuser

# Lancer les tests
test *args='':
    uv run python manage.py test {{args}}

# Lancer les tests avec coverage
coverage :
    docker compose exec koobfood coverage run manage.py test

# Afficher le rapport de coverage
report:
    docker compose exec koobfood coverage report

# Nettoyer les fichiers inutiles
clean:
    Get-ChildItem -Recurse -Include "__pycache__", "*.pyc" | Remove-Item -Recurse -Force

# Installer les dépendances
install-deps:
    uv add -r requirements.txt

# Supprimer les dépendances
remove-deps:
    uv remove -r requirements.txt

# Installer les packages
add package:
    uv add {{package}}

# Voir les URLs
urls:
    docker compose exec koobfood uv run manage.py show_urls

# Build toutes les images Docker
build-all:
    docker compose up --build -d

# Build une image Docker
build image:
    docker compose build {{image}}

# Démarrer les conteneurs Docker
up:
    docker compose up -d

# Stopper les conteneurs Docker
down:
    docker compose down

# Stopper les conteneurs Docker et supprimer les volumes
down-v:
    docker compose down -v

# Redémarrer les conteneurs Docker
restart service:
    docker compose restart {{service}}

# Naviguer dans le python shell
shell:
    uv run python manage.py shell_plus

# Suivre les logs d'un service Docker
logs service:
    docker compose logs -f {{service}}


# Installation complète du projet (installe toutes les dépendances via UV)
init:
    uv add -r requirements.txt
    just makemigrations
    just migrate
    just run


# $env:DJANGO_MODE="production"
# $env:DJANGO_MODE="test"
# $env:DJANGO_MODE="local"

# from django.conf import settings
# print(settings.DATABASES["default"])
# print(settings.DEBUG)