# Generated by Django 5.2.5 on 2025-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_table_manager_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
